import type { ConstructionRulePack } from '../schema/rulepacks'

export const CONSTRUCTION_COMPILER_VERSION = '0.1.0'

export const DEFAULT_RULE_PACK: ConstructionRulePack = {
  id: 'us-residential-v1',
  label: 'US Residential Baseline',
  locale: 'en-US',
  currency: 'USD',
  compilerVersion: CONSTRUCTION_COMPILER_VERSION,
  preferredStockLengths: [8, 10, 12, 14, 16],
  wasteFactors: {
    framing: 0.1,
    sheathing: 0.08,
    drywall: 0.06,
    trim: 0.12,
  },
  openingFallbacks: {
    defaultDoorSillHeight: 0,
    defaultWindowSillHeight: 0.9,
  },
  defaults: {
    interiorWallAssemblyId: 'wall-2x4-interior',
    exteriorWallAssemblyId: 'wall-2x6-exterior',
    floorAssemblyId: 'floor-slab-on-grade',
    roofAssemblyId: 'roof-rafters-generic',
    finishAssemblyId: 'finish-generic',
    mepAssemblyId: 'mep-generic',
  },
  costRules: {
    'lumber.spf.2x4': {
      code: 'lumber.spf.2x4',
      label: 'SPF 2x4 lumber',
      unit: 'lf',
      unitCost: 1.2,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'lumber.spf.2x6': {
      code: 'lumber.spf.2x6',
      label: 'SPF 2x6 lumber',
      unit: 'lf',
      unitCost: 1.55,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'lumber.spf.2x8': {
      code: 'lumber.spf.2x8',
      label: 'SPF 2x8 header stock',
      unit: 'lf',
      unitCost: 2.1,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'lumber.spf.2x10': {
      code: 'lumber.spf.2x10',
      label: 'SPF 2x10 header stock',
      unit: 'lf',
      unitCost: 2.85,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'panel.osb.7-16.4x8': {
      code: 'panel.osb.7-16.4x8',
      label: '7/16 in OSB 4x8',
      unit: 'sheet',
      unitCost: 22,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 16 13',
      defaultWasteFactor: 0.08,
    },
    'panel.gwb.1-2.4x8': {
      code: 'panel.gwb.1-2.4x8',
      label: '1/2 in gypsum board 4x8',
      unit: 'sheet',
      unitCost: 18,
      currency: 'USD',
      uniformatCode: 'C3020',
      masterformatCode: '09 29 00',
      defaultWasteFactor: 0.06,
    },
    'trim.casing.2-1-4': {
      code: 'trim.casing.2-1-4',
      label: 'Casing 2-1/4 in',
      unit: 'lf',
      unitCost: 0.85,
      currency: 'USD',
      uniformatCode: 'C3020',
      masterformatCode: '06 22 00',
      defaultWasteFactor: 0.12,
    },
    'floor.joist': {
      code: 'floor.joist',
      label: 'Dimensional floor joist',
      unit: 'lf',
      unitCost: 2.9,
      currency: 'USD',
      uniformatCode: 'B1010',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'floor.i-joist': {
      code: 'floor.i-joist',
      label: 'I-joist floor member',
      unit: 'lf',
      unitCost: 4.1,
      currency: 'USD',
      uniformatCode: 'B1010',
      masterformatCode: '06 17 53',
      defaultWasteFactor: 0.08,
    },
    'floor.truss': {
      code: 'floor.truss',
      label: 'Open-web floor truss',
      unit: 'lf',
      unitCost: 5.2,
      currency: 'USD',
      uniformatCode: 'B1010',
      masterformatCode: '06 17 53',
      defaultWasteFactor: 0.08,
    },
    'roof.truss': {
      code: 'roof.truss',
      label: 'Roof truss framing',
      unit: 'lf',
      unitCost: 5.8,
      currency: 'USD',
      uniformatCode: 'B1020',
      masterformatCode: '06 17 53',
      defaultWasteFactor: 0.08,
    },
    'roof.rafter': {
      code: 'roof.rafter',
      label: 'Roof rafter framing',
      unit: 'lf',
      unitCost: 3.4,
      currency: 'USD',
      uniformatCode: 'B1020',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'mep.panel.main': {
      code: 'mep.panel.main',
      label: 'Main electrical panel',
      unit: 'ea',
      unitCost: 1200,
      currency: 'USD',
      uniformatCode: 'D5010',
      masterformatCode: '26 24 16',
      defaultWasteFactor: 0,
    },
    'mep.device.box': {
      code: 'mep.device.box',
      label: 'Electrical device box',
      unit: 'ea',
      unitCost: 8,
      currency: 'USD',
      uniformatCode: 'D5020',
      masterformatCode: '26 27 26',
      defaultWasteFactor: 0.05,
    },
    'mep.light.fixture': {
      code: 'mep.light.fixture',
      label: 'Residential light fixture allowance',
      unit: 'ea',
      unitCost: 42,
      currency: 'USD',
      uniformatCode: 'D5020',
      masterformatCode: '26 51 19',
      defaultWasteFactor: 0.02,
    },
    'mep.wire.nm-b.12-2': {
      code: 'mep.wire.nm-b.12-2',
      label: 'NM-B 12/2 cable',
      unit: 'lf',
      unitCost: 0.72,
      currency: 'USD',
      uniformatCode: 'D5020',
      masterformatCode: '26 05 19',
      defaultWasteFactor: 0.1,
    },
    'mep.wire.nm-b.14-3': {
      code: 'mep.wire.nm-b.14-3',
      label: 'NM-B 14/3 cable',
      unit: 'lf',
      unitCost: 0.94,
      currency: 'USD',
      uniformatCode: 'D5020',
      masterformatCode: '26 05 19',
      defaultWasteFactor: 0.1,
    },
    'plumbing.pipe.pex': {
      code: 'plumbing.pipe.pex',
      label: 'PEX supply piping',
      unit: 'lf',
      unitCost: 1.85,
      currency: 'USD',
      uniformatCode: 'D2020',
      masterformatCode: '22 11 16',
      defaultWasteFactor: 0.08,
    },
    'plumbing.pipe.pvc': {
      code: 'plumbing.pipe.pvc',
      label: 'PVC sanitary / vent piping',
      unit: 'lf',
      unitCost: 2.35,
      currency: 'USD',
      uniformatCode: 'D2030',
      masterformatCode: '22 13 16',
      defaultWasteFactor: 0.08,
    },
    'plumbing.fixture.generic': {
      code: 'plumbing.fixture.generic',
      label: 'Residential plumbing fixture allowance',
      unit: 'ea',
      unitCost: 185,
      currency: 'USD',
      uniformatCode: 'D2010',
      masterformatCode: '22 40 00',
      defaultWasteFactor: 0.03,
    },
    'foundation.concrete.footing': {
      code: 'foundation.concrete.footing',
      label: 'Continuous concrete footing',
      unit: 'lf',
      unitCost: 24,
      currency: 'USD',
      uniformatCode: 'A1010',
      masterformatCode: '03 30 00',
      defaultWasteFactor: 0.05,
    },
    'foundation.concrete.stem-wall': {
      code: 'foundation.concrete.stem-wall',
      label: 'Concrete stem wall',
      unit: 'lf',
      unitCost: 38,
      currency: 'USD',
      uniformatCode: 'A1010',
      masterformatCode: '03 30 00',
      defaultWasteFactor: 0.05,
    },
    'foundation.concrete.pier': {
      code: 'foundation.concrete.pier',
      label: 'Concrete pier',
      unit: 'ea',
      unitCost: 165,
      currency: 'USD',
      uniformatCode: 'A1010',
      masterformatCode: '03 30 00',
      defaultWasteFactor: 0.03,
    },
  },
}

export const DEFAULT_CONSTRUCTION_RULEPACK = DEFAULT_RULE_PACK
