import type { ConstructionRulePack } from '../schema/rulepacks'

export const CONSTRUCTION_COMPILER_VERSION = '0.1.0'

export const DEFAULT_RULE_PACK: ConstructionRulePack = {
  id: 'us-residential-v1',
  label: 'US Residential Baseline',
  locale: 'en-US',
  currency: 'USD',
  compilerVersion: CONSTRUCTION_COMPILER_VERSION,
  preferredStockLengths: [8, 10, 12, 14, 16],
  wasteFactors: {
    framing: 0.1,
    sheathing: 0.08,
    drywall: 0.06,
    trim: 0.12,
  },
  openingFallbacks: {
    defaultDoorSillHeight: 0,
    defaultWindowSillHeight: 0.9,
  },
  defaults: {
    interiorWallAssemblyId: 'wall-2x4-interior',
    exteriorWallAssemblyId: 'wall-2x6-exterior',
    floorAssemblyId: 'floor-slab-on-grade',
    roofAssemblyId: 'roof-rafters-generic',
    finishAssemblyId: 'finish-generic',
    mepAssemblyId: 'mep-generic',
  },
  costRules: {
    'lumber.spf.2x4': {
      code: 'lumber.spf.2x4',
      label: 'SPF 2x4 lumber',
      unit: 'lf',
      unitCost: 1.2,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'lumber.spf.2x6': {
      code: 'lumber.spf.2x6',
      label: 'SPF 2x6 lumber',
      unit: 'lf',
      unitCost: 1.55,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'lumber.spf.2x8': {
      code: 'lumber.spf.2x8',
      label: 'SPF 2x8 header stock',
      unit: 'lf',
      unitCost: 2.1,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'lumber.spf.2x10': {
      code: 'lumber.spf.2x10',
      label: 'SPF 2x10 header stock',
      unit: 'lf',
      unitCost: 2.85,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 11 00',
      defaultWasteFactor: 0.1,
    },
    'panel.osb.7-16.4x8': {
      code: 'panel.osb.7-16.4x8',
      label: '7/16 in OSB 4x8',
      unit: 'sheet',
      unitCost: 22,
      currency: 'USD',
      uniformatCode: 'B2010',
      masterformatCode: '06 16 13',
      defaultWasteFactor: 0.08,
    },
    'panel.gwb.1-2.4x8': {
      code: 'panel.gwb.1-2.4x8',
      label: '1/2 in gypsum board 4x8',
      unit: 'sheet',
      unitCost: 18,
      currency: 'USD',
      uniformatCode: 'C3020',
      masterformatCode: '09 29 00',
      defaultWasteFactor: 0.06,
    },
    'trim.casing.2-1-4': {
      code: 'trim.casing.2-1-4',
      label: 'Casing 2-1/4 in',
      unit: 'lf',
      unitCost: 0.85,
      currency: 'USD',
      uniformatCode: 'C3020',
      masterformatCode: '06 22 00',
      defaultWasteFactor: 0.12,
    },
  },
}

export const DEFAULT_CONSTRUCTION_RULEPACK = DEFAULT_RULE_PACK
